# 1. 导入库

In [2]:
import pandas as pd
import numpy as np

# 2. 读取数据

In [3]:
# df_lines = pd.read_csv('./TransportData/nanjing_lines.csv',names=['id','line_name','lines','price','station_names','station_coords'])
df_lines = pd.read_csv('./data_api_org/nanjing_lines.csv',names=['id','line_name','lines','price','station_names','station_coords'])
df_lines.head(2)

,id,line_name,lines,price,station_names,station_coords
0,0,雨经开1号线(刘村地铁站--刘村地铁站),"118.66494,31.94438;118.66494,31.944379;118.664...",2,"['刘村地铁站', '招呼站', '龙藏大道·凤集大道', '凤集大道东', '凤集大道·龙...","['118.66494,31.94438', '118.65957,31.942728', ..."
1,0,16路(龙福山庄总站--中山码头北),"118.758173,31.997193;118.758264,31.997166;118....",2,"['龙福山庄总站', '赛上路', '凤台南路', '赛虹桥', '赛虹桥立交东', '中华...","['118.758173,31.997193', '118.757852,32.003963..."

In [4]:
len(df_lines)

143

# 3.站点数据清洗

In [5]:
df_sts = df_lines[['station_coords','station_names']]
df_sts.head(1)

,station_coords,station_names
0,"['118.66494,31.94438', '118.65957,31.942728', ...","['刘村地铁站', '招呼站', '龙藏大道·凤集大道', '凤集大道东', '凤集大道·龙..."

In [6]:
df_sts['station_coords'][0]

"['118.66494,31.94438', '118.65957,31.942728', '118.650987,31.936086', '118.663824,31.926168', '118.65717,31.928186', '118.642603,31.930751', '118.639277,31.931412', '118.637064,31.929623', '118.634859,31.927836', '118.632478,31.921535', '118.626949,31.926362', '118.630307,31.930465', '118.634327,31.932726', '118.636673,31.933811', '118.640055,31.93626', '118.644242,31.939823', '118.643396,31.945787', '118.65681,31.943991', '118.665047,31.944169']"

In [7]:
df_sts['station_coords'][0].replace('[','').replace(']','').replace('\'','').split(', ')

['118.66494,31.94438',
 '118.65957,31.942728',
 '118.650987,31.936086',
 '118.663824,31.926168',
 '118.65717,31.928186',
 '118.642603,31.930751',
 '118.639277,31.931412',
 '118.637064,31.929623',
 '118.634859,31.927836',
 '118.632478,31.921535',
 '118.626949,31.926362',
 '118.630307,31.930465',
 '118.634327,31.932726',
 '118.636673,31.933811',
 '118.640055,31.93626',
 '118.644242,31.939823',
 '118.643396,31.945787',
 '118.65681,31.943991',
 '118.665047,31.944169']

In [8]:
df_sts['station_coords']=df_sts['station_coords'].apply(lambda x:x.replace('[','').replace(']','').split(', '))

C:\Users\8888\AppData\Local\Temp\ipykernel_5880\1626323695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sts['station_coords']=df_sts['station_coords'].apply(lambda x:x.replace('[','').replace(']','').split(', '))

In [9]:
df_sts['station_coords'][0]

["'118.66494,31.94438'",
 "'118.65957,31.942728'",
 "'118.650987,31.936086'",
 "'118.663824,31.926168'",
 "'118.65717,31.928186'",
 "'118.642603,31.930751'",
 "'118.639277,31.931412'",
 "'118.637064,31.929623'",
 "'118.634859,31.927836'",
 "'118.632478,31.921535'",
 "'118.626949,31.926362'",
 "'118.630307,31.930465'",
 "'118.634327,31.932726'",
 "'118.636673,31.933811'",
 "'118.640055,31.93626'",
 "'118.644242,31.939823'",
 "'118.643396,31.945787'",
 "'118.65681,31.943991'",
 "'118.665047,31.944169'"]

In [10]:
len(df_sts['station_coords'][0])

19

In [11]:
df_sts['station_names'][0]

"['刘村地铁站', '招呼站', '龙藏大道·凤集大道', '凤集大道东', '凤集大道·龙飞路', '招呼站', '招呼站(龙盛路)', '招呼站', '招呼站(凤汇大厦B座)', '招呼站', '招呼站(龙腾南路)', '招呼站', '数出大厦', '雨花创业园', '三鸿', '星滨路南(招呼站)', '星滨路北(招呼站)', '雨盛路(招呼站)', '刘村地铁站']"

In [12]:
df_sts['station_names']=df_sts['station_names'].apply(lambda x:x.replace('[','').replace(']','').replace('\'','').split(', '))

C:\Users\8888\AppData\Local\Temp\ipykernel_5880\310525467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sts['station_names']=df_sts['station_names'].apply(lambda x:x.replace('[','').replace(']','').replace('\'','').split(', '))

In [13]:
df_sts['station_names'][0]

['刘村地铁站',
 '招呼站',
 '龙藏大道·凤集大道',
 '凤集大道东',
 '凤集大道·龙飞路',
 '招呼站',
 '招呼站(龙盛路)',
 '招呼站',
 '招呼站(凤汇大厦B座)',
 '招呼站',
 '招呼站(龙腾南路)',
 '招呼站',
 '数出大厦',
 '雨花创业园',
 '三鸿',
 '星滨路南(招呼站)',
 '星滨路北(招呼站)',
 '雨盛路(招呼站)',
 '刘村地铁站']

In [14]:
df_sts.head(1)

,station_coords,station_names
0,"['118.66494,31.94438', '118.65957,31.942728', ...","[刘村地铁站, 招呼站, 龙藏大道·凤集大道, 凤集大道东, 凤集大道·龙飞路, 招呼站, ..."

In [15]:
 np.hstack(df_sts['station_names'].repeat(list(map(len,df_sts['station_names']))))

array(['刘村地铁站', '招呼站', '龙藏大道·凤集大道', ..., '能仁里', '安德门地铁站', '菊花台公园'],
      dtype='<U14')

In [17]:
np.hstack(df_sts['station_coords'].repeat(list(map(len,df_sts['station_coords']))))

array(["'118.66494,31.94438'", "'118.65957,31.942728'",
       "'118.650987,31.936086'", ..., "'118.768415,31.999961'",
       "'118.76223,31.991457'", "'118.761815,31.98859'"], dtype='<U22')

In [16]:
df_sts.columns

Index(['station_coords', 'station_names'], dtype='object')

In [18]:
st_all = pd.DataFrame(\
                    np.column_stack((\
                                    np.hstack(df_sts['station_coords'].repeat(list(map(len,df_sts['station_coords'])))),
                                    np.hstack(df_sts['station_names'].repeat(list(map(len,df_sts['station_names']))))
                                    )),
                                     columns=['station_coords','station_names']
                    )
st_all

                station_coords station_names
0         '118.66494,31.94438'         刘村地铁站
1        '118.65957,31.942728'           招呼站
2       '118.650987,31.936086'     龙藏大道·凤集大道
3       '118.663824,31.926168'         凤集大道东
4        '118.65717,31.928186'      凤集大道·龙飞路
...                        ...           ...
103982  '118.775006,32.005415'         雨花西路北
103983  '118.771111,32.003525'          雨花西路
103984  '118.768415,31.999961'           能仁里
103985   '118.76223,31.991457'        安德门地铁站
103986   '118.761815,31.98859'         菊花台公园

[103987 rows x 2 columns]

In [19]:
len(st_all)

103987

In [20]:
st_all=st_all.drop_duplicates()
len(st_all)

2546

In [21]:
# st_all.to_csv('station.csv')
st_all.to_csv('./amap/station_2.csv')

# 4.线路数据清洗

In [22]:
df_lines.columns

Index(['id', 'line_name', 'lines', 'price', 'station_names', 'station_coords'], dtype='object')

In [23]:
df_ls=df_lines[['line_name','lines']]
df_ls.head(2)

              line_name                                              lines
0  雨经开1号线(刘村地铁站--刘村地铁站)  118.66494,31.94438;118.66494,31.944379;118.664...
1    16路(龙福山庄总站--中山码头北)  118.758173,31.997193;118.758264,31.997166;118....

In [24]:
df_ls['lines'][0]

'118.66494,31.94438;118.66494,31.944379;118.664075,31.943875;118.663818,31.943725;118.66209,31.942716;118.661151,31.942169;118.66032,31.943188;118.660181,31.943086;118.659874,31.942906;118.659873,31.942906;118.65957,31.942728;118.659167,31.942491;118.658389,31.94203;118.657949,31.941778;118.657783,31.941677;118.657568,31.941547;118.657531,31.941504;118.657482,31.941391;118.657402,31.941327;118.658383,31.940544;118.656844,31.939605;118.655615,31.938854;118.655476,31.938763;118.653169,31.937395;118.652928,31.937255;118.652343,31.936912;118.652268,31.936864;118.651431,31.93637;118.651131,31.936188;118.650986,31.936086;118.650987,31.936086;118.650986,31.936086;118.650755,31.935925;118.650224,31.935501;118.649623,31.935018;118.648867,31.934423;118.648717,31.934321;118.648443,31.93423;118.648014,31.93416;118.647912,31.934176;118.647821,31.934176;118.64766,31.934155;118.64751,31.934106;118.647451,31.93408;118.647365,31.934036;118.647279,31.933967;118.647231,31.933919;118.647166,31.933838;118.647102,31.93372;118.647075,31.93364;118.647065,31.933554;118.647065,31.933452;118.647075,31.933398;118.647108,31.933286;118.647145,31.9332;118.647225,31.933098;118.647274,31.93305;118.64737,31.932975;118.64744,31.932931;118.64758,31.932878;118.647714,31.932856;118.647746,31.932851;118.647939,31.93284;118.648373,31.932755;118.648524,31.932685;118.648636,31.932615;118.649521,31.931859;118.650755,31.930796;118.651345,31.930298;118.651893,31.929868;118.652118,31.929702;118.652338,31.929563;118.652343,31.929557;118.652837,31.929305;118.65354,31.929031;118.6545,31.928736;118.65458,31.92871;118.655567,31.928409;118.656463,31.928136;118.656554,31.928103;118.657675,31.92776;118.659,31.927342;118.660771,31.926757;118.661908,31.926398;118.662326,31.926269;118.662965,31.92607;118.664011,31.925738;118.664252,31.926038;118.663825,31.92617;118.663824,31.926168;118.663506,31.926269;118.662927,31.926451;118.661961,31.926752;118.660937,31.927068;118.659097,31.927589;118.657928,31.927953;118.657868,31.92797;118.65717,31.928186;118.656833,31.928291;118.656699,31.928334;118.655669,31.928656;118.654848,31.928914;118.654752,31.928946;118.653496,31.929327;118.652976,31.92953;118.652735,31.929643;118.652461,31.929799;118.652343,31.929874;118.65208,31.930056;118.651775,31.930287;118.650975,31.930973;118.64964,31.932138;118.649023,31.932663;118.648781,31.932905;118.648695,31.933033;118.648599,31.933328;118.64862,31.933404;118.648631,31.9335;118.648631,31.933602;118.64861,31.933688;118.64855,31.933811;118.648508,31.933876;118.648411,31.933972;118.648288,31.934063;118.64817,31.934117;118.648014,31.93416;118.647912,31.934176;118.647821,31.934176;118.64766,31.934155;118.64751,31.934106;118.647451,31.93408;118.647365,31.934036;118.647279,31.933967;118.647231,31.933919;118.647166,31.933838;118.647102,31.93372;118.647075,31.93364;118.647065,31.933554;118.647065,31.933452;118.647075,31.933398;118.646925,31.932969;118.646764,31.932781;118.646528,31.932578;118.645546,31.9318;118.645503,31.931762;118.643358,31.930067;118.642603,31.930751;118.641985,31.931311;118.640649,31.932492;118.640568,31.932476;118.639898,31.931923;118.639517,31.931606;118.639276,31.931411;118.639277,31.931412;118.639007,31.931193;118.638793,31.931011;118.638578,31.93084;118.637993,31.930373;118.637414,31.929906;118.637064,31.929623;118.637063,31.929623;118.636668,31.929305;118.635982,31.928736;118.635815,31.928597;118.634858,31.927836;118.634859,31.927836;118.634858,31.927836;118.633375,31.926655;118.633135,31.926464;118.633136,31.926464;118.633135,31.926464;118.632892,31.926269;118.632801,31.926194;118.633584,31.925593;118.63427,31.925062;118.634292,31.925046;118.634693,31.924738;118.635032,31.924477;118.635906,31.923801;118.63301,31.921125;118.632478,31.921535;118.631266,31.922471;118.63037,31.923168;118.630011,31.923442;118.629915,31.923522;118.629705,31.923683;118.628997,31.924188;118.627436,31.925276;118.627415,31.925293;118.626551,31.925877;118.626873,31.926269;118.626948,31.926361;118.626949,31.926362;118.62757,31.927127;118.628107,31.927798;118.628418,31.928184;118.628665,31.928511;118.629126,31.929053;118.629512,31.929541;118.630016,31.930153;118.630118,31.930265;118.630307,31.930465;118.63037,31.930523;118.630564,31.930695;118.630885,31.930957;118.631159,31.931151;118.631486,31.931354;118.632237,31.931757;118.63242,31.931848;118.633766,31.93247;118.634327,31.932726;118.634989,31.933028;118.636672,31.933811;118.636673,31.933811;118.636936,31.933935;118.637285,31.934106;118.637478,31.934192;118.637983,31.93446;118.638176,31.934573;118.638245,31.934621;118.638471,31.934793;118.638798,31.935077;118.639962,31.936172;118.640055,31.93626;118.640054,31.93626;118.640208,31.936408;118.640289,31.936483;118.640568,31.936746;118.640697,31.936874;118.64111,31.937255;118.642167,31.938237;118.642381,31.938435;118.643068,31.93909;118.643315,31.939294;118.643486,31.939417;118.643803,31.93961;118.644241,31.939823;118.644242,31.939823;118.644241,31.939823;118.644313,31.939857;118.645632,31.940398;118.645621,31.940495;118.644575,31.943001;118.644366,31.943489;118.643969,31.944428;118.64383,31.944771;118.643486,31.94557;118.643396,31.945787;118.643186,31.946294;118.642816,31.94711;118.64273,31.947389;118.645166,31.947491;118.646882,31.947566;118.648191,31.94763;118.648395,31.947641;118.64986,31.94771;118.650423,31.947737;118.651565,31.947791;118.652145,31.947818;118.652343,31.947828;118.652821,31.94785;118.653368,31.947871;118.657155,31.948043;118.657155,31.947464;118.657171,31.946965;118.657187,31.946858;118.657214,31.946788;118.656801,31.946552;118.656393,31.946326;118.656259,31.946246;118.656028,31.946112;118.655868,31.946021;118.655406,31.945753;118.655808,31.945216;118.655905,31.945087;118.656082,31.944867;118.656146,31.944787;118.656495,31.944379;118.656726,31.944095;118.65681,31.943991;118.657101,31.943633;118.657584,31.943038;118.657826,31.942732;118.658078,31.942421;118.658389,31.94203;118.659167,31.942491;118.660181,31.943086;118.661017,31.942089;118.661313,31.941992;118.662487,31.942695;118.663984,31.943542;118.664225,31.943687;118.665046,31.944168;118.665047,31.944169'

In [25]:
df_ls['lines'][0].split(';')

['118.66494,31.94438',
 '118.66494,31.944379',
 '118.664075,31.943875',
 '118.663818,31.943725',
 '118.66209,31.942716',
 '118.661151,31.942169',
 '118.66032,31.943188',
 '118.660181,31.943086',
 '118.659874,31.942906',
 '118.659873,31.942906',
 '118.65957,31.942728',
 '118.659167,31.942491',
 '118.658389,31.94203',
 '118.657949,31.941778',
 '118.657783,31.941677',
 '118.657568,31.941547',
 '118.657531,31.941504',
 '118.657482,31.941391',
 '118.657402,31.941327',
 '118.658383,31.940544',
 '118.656844,31.939605',
 '118.655615,31.938854',
 '118.655476,31.938763',
 '118.653169,31.937395',
 '118.652928,31.937255',
 '118.652343,31.936912',
 '118.652268,31.936864',
 '118.651431,31.93637',
 '118.651131,31.936188',
 '118.650986,31.936086',
 '118.650987,31.936086',
 '118.650986,31.936086',
 '118.650755,31.935925',
 '118.650224,31.935501',
 '118.649623,31.935018',
 '118.648867,31.934423',
 '118.648717,31.934321',
 '118.648443,31.93423',
 '118.648014,31.93416',
 '118.647912,31.934176',
 '118.647821,31.934176',
 '118.64766,31.934155',
 '118.64751,31.934106',
 '118.647451,31.93408',
 '118.647365,31.934036',
 '118.647279,31.933967',
 '118.647231,31.933919',
 '118.647166,31.933838',
 '118.647102,31.93372',
 '118.647075,31.93364',
 '118.647065,31.933554',
 '118.647065,31.933452',
 '118.647075,31.933398',
 '118.647108,31.933286',
 '118.647145,31.9332',
 '118.647225,31.933098',
 '118.647274,31.93305',
 '118.64737,31.932975',
 '118.64744,31.932931',
 '118.64758,31.932878',
 '118.647714,31.932856',
 '118.647746,31.932851',
 '118.647939,31.93284',
 '118.648373,31.932755',
 '118.648524,31.932685',
 '118.648636,31.932615',
 '118.649521,31.931859',
 '118.650755,31.930796',
 '118.651345,31.930298',
 '118.651893,31.929868',
 '118.652118,31.929702',
 '118.652338,31.929563',
 '118.652343,31.929557',
 '118.652837,31.929305',
 '118.65354,31.929031',
 '118.6545,31.928736',
 '118.65458,31.92871',
 '118.655567,31.928409',
 '118.656463,31.928136',
 '118.656554,31.928103',
 '118.657675,31.92776',
 '118.659,31.927342',
 '118.660771,31.926757',
 '118.661908,31.926398',
 '118.662326,31.926269',
 '118.662965,31.92607',
 '118.664011,31.925738',
 '118.664252,31.926038',
 '118.663825,31.92617',
 '118.663824,31.926168',
 '118.663506,31.926269',
 '118.662927,31.926451',
 '118.661961,31.926752',
 '118.660937,31.927068',
 '118.659097,31.927589',
 '118.657928,31.927953',
 '118.657868,31.92797',
 '118.65717,31.928186',
 '118.656833,31.928291',
 '118.656699,31.928334',
 '118.655669,31.928656',
 '118.654848,31.928914',
 '118.654752,31.928946',
 '118.653496,31.929327',
 '118.652976,31.92953',
 '118.652735,31.929643',
 '118.652461,31.929799',
 '118.652343,31.929874',
 '118.65208,31.930056',
 '118.651775,31.930287',
 '118.650975,31.930973',
 '118.64964,31.932138',
 '118.649023,31.932663',
 '118.648781,31.932905',
 '118.648695,31.933033',
 '118.648599,31.933328',
 '118.64862,31.933404',
 '118.648631,31.9335',
 '118.648631,31.933602',
 '118.64861,31.933688',
 '118.64855,31.933811',
 '118.648508,31.933876',
 '118.648411,31.933972',
 '118.648288,31.934063',
 '118.64817,31.934117',
 '118.648014,31.93416',
 '118.647912,31.934176',
 '118.647821,31.934176',
 '118.64766,31.934155',
 '118.64751,31.934106',
 '118.647451,31.93408',
 '118.647365,31.934036',
 '118.647279,31.933967',
 '118.647231,31.933919',
 '118.647166,31.933838',
 '118.647102,31.93372',
 '118.647075,31.93364',
 '118.647065,31.933554',
 '118.647065,31.933452',
 '118.647075,31.933398',
 '118.646925,31.932969',
 '118.646764,31.932781',
 '118.646528,31.932578',
 '118.645546,31.9318',
 '118.645503,31.931762',
 '118.643358,31.930067',
 '118.642603,31.930751',
 '118.641985,31.931311',
 '118.640649,31.932492',
 '118.640568,31.932476',
 '118.639898,31.931923',
 '118.639517,31.931606',
 '118.639276,31.931411',
 '118.639277,31.931412',
 '118.639007,31.931193',
 '118.638793,31.931011',
 '118.638578,31.93084',
 '118.637993,31.930373',
 '118.637414,31.929906',
 '118.637064,31.929623',
 '118.637063,31.929623',
 '118.636668,31.929305',
 '118.635982,31.928736',
 '118.635815,31.928597',
 '118.634858,31.927836',
 '118.634859,31.927836',
 '118.634858,31.927836',
 '118.633375,31.926655',
 '118.633135,31.926464',
 '118.633136,31.926464',
 '118.633135,31.926464',
 '118.632892,31.926269',
 '118.632801,31.926194',
 '118.633584,31.925593',
 '118.63427,31.925062',
 '118.634292,31.925046',
 '118.634693,31.924738',
 '118.635032,31.924477',
 '118.635906,31.923801',
 '118.63301,31.921125',
 '118.632478,31.921535',
 '118.631266,31.922471',
 '118.63037,31.923168',
 '118.630011,31.923442',
 '118.629915,31.923522',
 '118.629705,31.923683',
 '118.628997,31.924188',
 '118.627436,31.925276',
 '118.627415,31.925293',
 '118.626551,31.925877',
 '118.626873,31.926269',
 '118.626948,31.926361',
 '118.626949,31.926362',
 '118.62757,31.927127',
 '118.628107,31.927798',
 '118.628418,31.928184',
 '118.628665,31.928511',
 '118.629126,31.929053',
 '118.629512,31.929541',
 '118.630016,31.930153',
 '118.630118,31.930265',
 '118.630307,31.930465',
 '118.63037,31.930523',
 '118.630564,31.930695',
 '118.630885,31.930957',
 '118.631159,31.931151',
 '118.631486,31.931354',
 '118.632237,31.931757',
 '118.63242,31.931848',
 '118.633766,31.93247',
 '118.634327,31.932726',
 '118.634989,31.933028',
 '118.636672,31.933811',
 '118.636673,31.933811',
 '118.636936,31.933935',
 '118.637285,31.934106',
 '118.637478,31.934192',
 '118.637983,31.93446',
 '118.638176,31.934573',
 '118.638245,31.934621',
 '118.638471,31.934793',
 '118.638798,31.935077',
 '118.639962,31.936172',
 '118.640055,31.93626',
 '118.640054,31.93626',
 '118.640208,31.936408',
 '118.640289,31.936483',
 '118.640568,31.936746',
 '118.640697,31.936874',
 '118.64111,31.937255',
 '118.642167,31.938237',
 '118.642381,31.938435',
 '118.643068,31.93909',
 '118.643315,31.939294',
 '118.643486,31.939417',
 '118.643803,31.93961',
 '118.644241,31.939823',
 '118.644242,31.939823',
 '118.644241,31.939823',
 '118.644313,31.939857',
 '118.645632,31.940398',
 '118.645621,31.940495',
 '118.644575,31.943001',
 '118.644366,31.943489',
 '118.643969,31.944428',
 '118.64383,31.944771',
 '118.643486,31.94557',
 '118.643396,31.945787',
 '118.643186,31.946294',
 '118.642816,31.94711',
 '118.64273,31.947389',
 '118.645166,31.947491',
 '118.646882,31.947566',
 '118.648191,31.94763',
 '118.648395,31.947641',
 '118.64986,31.94771',
 '118.650423,31.947737',
 '118.651565,31.947791',
 '118.652145,31.947818',
 '118.652343,31.947828',
 '118.652821,31.94785',
 '118.653368,31.947871',
 '118.657155,31.948043',
 '118.657155,31.947464',
 '118.657171,31.946965',
 '118.657187,31.946858',
 '118.657214,31.946788',
 '118.656801,31.946552',
 '118.656393,31.946326',
 '118.656259,31.946246',
 '118.656028,31.946112',
 '118.655868,31.946021',
 '118.655406,31.945753',
 '118.655808,31.945216',
 '118.655905,31.945087',
 '118.656082,31.944867',
 '118.656146,31.944787',
 '118.656495,31.944379',
 '118.656726,31.944095',
 '118.65681,31.943991',
 '118.657101,31.943633',
 '118.657584,31.943038',
 '118.657826,31.942732',
 '118.658078,31.942421',
 '118.658389,31.94203',
 '118.659167,31.942491',
 '118.660181,31.943086',
 '118.661017,31.942089',
 '118.661313,31.941992',
 '118.662487,31.942695',
 '118.663984,31.943542',
 '118.664225,31.943687',
 '118.665046,31.944168',
 '118.665047,31.944169']

In [26]:
df_ls['lines']=df_ls['lines'].apply(lambda x:x.split(';'))
df_ls['lines'][0]

C:\Users\8888\AppData\Local\Temp\ipykernel_5880\212454240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ls['lines']=df_ls['lines'].apply(lambda x:x.split(';'))

['118.66494,31.94438',
 '118.66494,31.944379',
 '118.664075,31.943875',
 '118.663818,31.943725',
 '118.66209,31.942716',
 '118.661151,31.942169',
 '118.66032,31.943188',
 '118.660181,31.943086',
 '118.659874,31.942906',
 '118.659873,31.942906',
 '118.65957,31.942728',
 '118.659167,31.942491',
 '118.658389,31.94203',
 '118.657949,31.941778',
 '118.657783,31.941677',
 '118.657568,31.941547',
 '118.657531,31.941504',
 '118.657482,31.941391',
 '118.657402,31.941327',
 '118.658383,31.940544',
 '118.656844,31.939605',
 '118.655615,31.938854',
 '118.655476,31.938763',
 '118.653169,31.937395',
 '118.652928,31.937255',
 '118.652343,31.936912',
 '118.652268,31.936864',
 '118.651431,31.93637',
 '118.651131,31.936188',
 '118.650986,31.936086',
 '118.650987,31.936086',
 '118.650986,31.936086',
 '118.650755,31.935925',
 '118.650224,31.935501',
 '118.649623,31.935018',
 '118.648867,31.934423',
 '118.648717,31.934321',
 '118.648443,31.93423',
 '118.648014,31.93416',
 '118.647912,31.934176',
 '118.647821,31.934176',
 '118.64766,31.934155',
 '118.64751,31.934106',
 '118.647451,31.93408',
 '118.647365,31.934036',
 '118.647279,31.933967',
 '118.647231,31.933919',
 '118.647166,31.933838',
 '118.647102,31.93372',
 '118.647075,31.93364',
 '118.647065,31.933554',
 '118.647065,31.933452',
 '118.647075,31.933398',
 '118.647108,31.933286',
 '118.647145,31.9332',
 '118.647225,31.933098',
 '118.647274,31.93305',
 '118.64737,31.932975',
 '118.64744,31.932931',
 '118.64758,31.932878',
 '118.647714,31.932856',
 '118.647746,31.932851',
 '118.647939,31.93284',
 '118.648373,31.932755',
 '118.648524,31.932685',
 '118.648636,31.932615',
 '118.649521,31.931859',
 '118.650755,31.930796',
 '118.651345,31.930298',
 '118.651893,31.929868',
 '118.652118,31.929702',
 '118.652338,31.929563',
 '118.652343,31.929557',
 '118.652837,31.929305',
 '118.65354,31.929031',
 '118.6545,31.928736',
 '118.65458,31.92871',
 '118.655567,31.928409',
 '118.656463,31.928136',
 '118.656554,31.928103',
 '118.657675,31.92776',
 '118.659,31.927342',
 '118.660771,31.926757',
 '118.661908,31.926398',
 '118.662326,31.926269',
 '118.662965,31.92607',
 '118.664011,31.925738',
 '118.664252,31.926038',
 '118.663825,31.92617',
 '118.663824,31.926168',
 '118.663506,31.926269',
 '118.662927,31.926451',
 '118.661961,31.926752',
 '118.660937,31.927068',
 '118.659097,31.927589',
 '118.657928,31.927953',
 '118.657868,31.92797',
 '118.65717,31.928186',
 '118.656833,31.928291',
 '118.656699,31.928334',
 '118.655669,31.928656',
 '118.654848,31.928914',
 '118.654752,31.928946',
 '118.653496,31.929327',
 '118.652976,31.92953',
 '118.652735,31.929643',
 '118.652461,31.929799',
 '118.652343,31.929874',
 '118.65208,31.930056',
 '118.651775,31.930287',
 '118.650975,31.930973',
 '118.64964,31.932138',
 '118.649023,31.932663',
 '118.648781,31.932905',
 '118.648695,31.933033',
 '118.648599,31.933328',
 '118.64862,31.933404',
 '118.648631,31.9335',
 '118.648631,31.933602',
 '118.64861,31.933688',
 '118.64855,31.933811',
 '118.648508,31.933876',
 '118.648411,31.933972',
 '118.648288,31.934063',
 '118.64817,31.934117',
 '118.648014,31.93416',
 '118.647912,31.934176',
 '118.647821,31.934176',
 '118.64766,31.934155',
 '118.64751,31.934106',
 '118.647451,31.93408',
 '118.647365,31.934036',
 '118.647279,31.933967',
 '118.647231,31.933919',
 '118.647166,31.933838',
 '118.647102,31.93372',
 '118.647075,31.93364',
 '118.647065,31.933554',
 '118.647065,31.933452',
 '118.647075,31.933398',
 '118.646925,31.932969',
 '118.646764,31.932781',
 '118.646528,31.932578',
 '118.645546,31.9318',
 '118.645503,31.931762',
 '118.643358,31.930067',
 '118.642603,31.930751',
 '118.641985,31.931311',
 '118.640649,31.932492',
 '118.640568,31.932476',
 '118.639898,31.931923',
 '118.639517,31.931606',
 '118.639276,31.931411',
 '118.639277,31.931412',
 '118.639007,31.931193',
 '118.638793,31.931011',
 '118.638578,31.93084',
 '118.637993,31.930373',
 '118.637414,31.929906',
 '118.637064,31.929623',
 '118.637063,31.929623',
 '118.636668,31.929305',
 '118.635982,31.928736',
 '118.635815,31.928597',
 '118.634858,31.927836',
 '118.634859,31.927836',
 '118.634858,31.927836',
 '118.633375,31.926655',
 '118.633135,31.926464',
 '118.633136,31.926464',
 '118.633135,31.926464',
 '118.632892,31.926269',
 '118.632801,31.926194',
 '118.633584,31.925593',
 '118.63427,31.925062',
 '118.634292,31.925046',
 '118.634693,31.924738',
 '118.635032,31.924477',
 '118.635906,31.923801',
 '118.63301,31.921125',
 '118.632478,31.921535',
 '118.631266,31.922471',
 '118.63037,31.923168',
 '118.630011,31.923442',
 '118.629915,31.923522',
 '118.629705,31.923683',
 '118.628997,31.924188',
 '118.627436,31.925276',
 '118.627415,31.925293',
 '118.626551,31.925877',
 '118.626873,31.926269',
 '118.626948,31.926361',
 '118.626949,31.926362',
 '118.62757,31.927127',
 '118.628107,31.927798',
 '118.628418,31.928184',
 '118.628665,31.928511',
 '118.629126,31.929053',
 '118.629512,31.929541',
 '118.630016,31.930153',
 '118.630118,31.930265',
 '118.630307,31.930465',
 '118.63037,31.930523',
 '118.630564,31.930695',
 '118.630885,31.930957',
 '118.631159,31.931151',
 '118.631486,31.931354',
 '118.632237,31.931757',
 '118.63242,31.931848',
 '118.633766,31.93247',
 '118.634327,31.932726',
 '118.634989,31.933028',
 '118.636672,31.933811',
 '118.636673,31.933811',
 '118.636936,31.933935',
 '118.637285,31.934106',
 '118.637478,31.934192',
 '118.637983,31.93446',
 '118.638176,31.934573',
 '118.638245,31.934621',
 '118.638471,31.934793',
 '118.638798,31.935077',
 '118.639962,31.936172',
 '118.640055,31.93626',
 '118.640054,31.93626',
 '118.640208,31.936408',
 '118.640289,31.936483',
 '118.640568,31.936746',
 '118.640697,31.936874',
 '118.64111,31.937255',
 '118.642167,31.938237',
 '118.642381,31.938435',
 '118.643068,31.93909',
 '118.643315,31.939294',
 '118.643486,31.939417',
 '118.643803,31.93961',
 '118.644241,31.939823',
 '118.644242,31.939823',
 '118.644241,31.939823',
 '118.644313,31.939857',
 '118.645632,31.940398',
 '118.645621,31.940495',
 '118.644575,31.943001',
 '118.644366,31.943489',
 '118.643969,31.944428',
 '118.64383,31.944771',
 '118.643486,31.94557',
 '118.643396,31.945787',
 '118.643186,31.946294',
 '118.642816,31.94711',
 '118.64273,31.947389',
 '118.645166,31.947491',
 '118.646882,31.947566',
 '118.648191,31.94763',
 '118.648395,31.947641',
 '118.64986,31.94771',
 '118.650423,31.947737',
 '118.651565,31.947791',
 '118.652145,31.947818',
 '118.652343,31.947828',
 '118.652821,31.94785',
 '118.653368,31.947871',
 '118.657155,31.948043',
 '118.657155,31.947464',
 '118.657171,31.946965',
 '118.657187,31.946858',
 '118.657214,31.946788',
 '118.656801,31.946552',
 '118.656393,31.946326',
 '118.656259,31.946246',
 '118.656028,31.946112',
 '118.655868,31.946021',
 '118.655406,31.945753',
 '118.655808,31.945216',
 '118.655905,31.945087',
 '118.656082,31.944867',
 '118.656146,31.944787',
 '118.656495,31.944379',
 '118.656726,31.944095',
 '118.65681,31.943991',
 '118.657101,31.943633',
 '118.657584,31.943038',
 '118.657826,31.942732',
 '118.658078,31.942421',
 '118.658389,31.94203',
 '118.659167,31.942491',
 '118.660181,31.943086',
 '118.661017,31.942089',
 '118.661313,31.941992',
 '118.662487,31.942695',
 '118.663984,31.943542',
 '118.664225,31.943687',
 '118.665046,31.944168',
 '118.665047,31.944169']

In [27]:
df_ls.head(2)

              line_name                                              lines
0  雨经开1号线(刘村地铁站--刘村地铁站)  [118.66494,31.94438, 118.66494,31.944379, 118....
1    16路(龙福山庄总站--中山码头北)  [118.758173,31.997193, 118.758264,31.997166, 1...

In [28]:
# df_ls.to_json(('lines.json'))
df_ls.to_json(('./amap/lines_2.json'))