In [2]:
from lxml import etree
import requests
# url ='http://www.planning.org.cn/news/newslist?cid=12&page=1'
url ='http://www.planning.org.cn/news/list?cid=12&page=1'
html = requests.get(url).text

In [3]:
html

'<!DOCTYPE HTML>\n<html xmlns="http://www.w3.org/1999/html">\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n    <title>规划动态-学会资讯-中国城市规划网</title>\n    <meta name="Keywords" content="城市规划新闻,城市规划资讯,城市规划热点,区域规划,低碳城市,户籍改革,总规修编,城镇群规划"/>\n    <meta name="description" content="发布规划资讯，行业热点，政策信息等，及时传递行业前沿信息。"/>\n    <link href="/css/common2025.css" rel="stylesheet" type="text/css">\n    <link href="/css/swiper-bundle.min.css" rel="stylesheet" type="text/css">\n    <link href="/css/index2025.css?version=2.0" rel="stylesheet" type="text/css">\n    <script type="text/javascript" src="/js/swiper-bundle.min.js"></script>\n    <script type="text/javascript" src="/js/jquery-3.7.1.min.js"></script>\n    <script type="text/javascript" src="/js/theia-sticky-sidebar.js"></script>\n</head>\n<body>\n<!-- head start -->\n\n<link href="/css/header_footer2025.css?version=1.0" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/jquery.lazyload.min.js"></script>\n\n<div class="header_line">\n\t<div class="flex_box_sb">\n\t\t<div class="flex_box_t">中国城市规划学会官方网站</div>\n\t\t<ul class="flex_box_t header_menu">\n\t\t\t<li><a href="https://en.planning.org.cn/">ENGLISH</a></li>\n\t\t\t<li><a href="" class="mosite"><i><img src="/images/svg/h3.svg"></i>手机版</a></li>\n\t\t\t<li><a href="/solicity/view_common?type=3&cid=5"><i><img src="/images/svg/h4.svg"></i>关于学会</a></li>\n\n\t\t\t\t\t\t<li><a href="/mb/login"><i><img src="/images/svg/h1.svg"></i>会员登录</a></li>\n\t\t\t\t\t</ul>\n\t</div>\n</div>\n<script type="text/javascript" src="/js/jquery.SuperSlide.2.1.3.js"></script>\n<script type="text/javascript">\n\tjQuery(".header_menu").slide({\n\t\ttype:"menu",// 效果类型，针对菜单/导航而引入的参数（默认slide）\n\t\ttitCell:".nli", //鼠标触发对象\n\t\ttargetCell:".sub", //titCell里面包含的要显示/消失的对象\n\t\teffect:"slideDown", //targetCell下拉效果\n\t\tdelayTime:300 , //效果时间\n\t\ttriggerTime:0, //鼠标延迟触发时间（默认150）\n\t\treturnDefault:true //鼠标移走后返回默认状态，例如默认频道是“预告片”，鼠标移走后会返回“预告片”（默认false）\n\t});\n</script>\n<div class="newyear_bg bg-white">\n<div class="header-logo flex_box_sb">\n\t<a href="/" class="logoenter"><img src="/images/svg/logo.svg" style="height:70px;"></a>\n    <!-- <h4><a href="javascript:void(0);" class="on">中</a><a href="http://en.planning.org.cn/" target="_blank">En</a></h4> -->\n\t<a href="https://member.planning.org.cn/" target="_blank" style="margin-left:140px;"><img src="/images/joinus2025.jpg" /></a>\n\t<div class="rg-search fr">\n\t\t<div id="uboxstyle">\n\t\t\t<select name="search-all" id="search-all">\n\t\t\t\t<option value="solicity" >学会</option>\n\t\t\t\t<option value="news" selected="selected">新闻</option>\n\t\t\t\t<option value="thesis" >论文</option>\n\t\t\t\t<option value="case" >案例</option>\n\t\t\t\t<option value="law" >政策法规</option>\n\t\t\t\t<option value="video" >会议视频</option>\n\t\t\t\t<option value="ppt" >PPT</option>\n\t\t\t\t<option value="report" >会议报告</option>\n\t\t\t</select>\n\t\t</div>\n\t\t<input id="head_schkey" type="text" name="head_schkey" class="init"  />\n\t\t<input value="" type="button" class="inent" onclick="headSearch()" />\n\t</div>\n</div>\n<div class="header-menu">\n\t<ul>\n\t\t<span><a href="/solicity/">学会</a></span>\n\t\t<li><a href="/solicity/view_common?type=3&cid=5">学会概况<i></i></a></li>\n\t\t<li class="w104"><a href="/#pp">品牌活动<i></i></a></li>\n\t\t<li><a href="/solicity/list?cid=3">国际合作<i></i></a></li>\n\t\t<li><a href="/solicity/list?cid=1">学会动态<i></i></a></li>\n\t\t<li><a href="/solicity/list?cid=2">分支机构动态<i></i></a></li>\n\t\t<li><a href="/solicity/list?cid=4">技术服务<i></i></a></li>\n\t</ul>\n\t<ul>\n\t\t<span><a href="/news/">资讯</a></span>\n\t\t<li><a href="/news/list?cid=11">学会声音<i></i></a></li>\n\t\t<li><a href="/news/list?cid=15">规划会客厅<i></i></a></li>\n        <li><a href="/news/list?cid=14">活动预告<i></i></a></li>\n        <li><a href="/news/list?cid=12">规划动态<i></i></a></li>\n        <li class="w90"><a href="/news/list?cid=13">深度报道<i></i></a></li>\n        <li><a href="/news/list?cid=16">招标信息<i></i></a></li>\n\t</ul>\n\t<ul>\n\t\t<span><a href="/resource/">资源</a></span>\n\t\t<li><a href="/thesis/">会议论文<i></i></a></li>\n        <li class="w80"><a href="http://v.planning.org.cn/" target="_blank">规划直播<i></i></a></li>\n        <li><a href="/zx/">学会咨询<i></i></a></li>\n        <li><a href="/case/">热点案例<i></i></a></li>\n        <li class="w80"><a href="/ppt/">会议 PPT<i></i></a></li>\n        <li><a href="/report/newslist">会议报告<i></i></a></li>\n\t</ul>\n\t<ul>\n\t\t<span><a href="/education/">教育</a></span>\n\t\t<li><a href="javascript:void(0);">培训信息<i></i></a></li><!--"/education/news"-->\n        <li><a href="/education/books?isme=1">学会出版<i></i></a></li>\n\t</ul>\n    <ul>\n\t\t<span><a href="/zt/">专题</a></span>\n\t</ul>\n</div>\n</div>\n<script type="text/javascript">\n\t$(document).ready(function(){\n\t\t$("img.lazy").lazyload({\n\t\t\tthreshold: 200, // 提前200像素加载\n\t\t\teffect: "fadeIn" // 淡入效果\n\t\t});\n\t\t// 背景图懒加载初始化\n\t\tif (\'IntersectionObserver\' in window) {\n\t\t\tvar lazyBgObserver = new IntersectionObserver(function(entries) {\n\t\t\t\tentries.forEach(function(entry) {\n\t\t\t\t\tif (entry.isIntersecting) {\n\t\t\t\t\t\tvar el = entry.target;\n\t\t\t\t\t\tvar bgUrl = el.getAttribute(\'data-background-original\');\n\t\t\t\t\t\tif (bgUrl) {\n\t\t\t\t\t\t\tel.style.backgroundImage = \'url(\' + bgUrl + \')\';\n\t\t\t\t\t\t\tel.style.backgroundSize = \'cover\';\n\t\t\t\t\t\t\tel.style.backgroundPosition = \'center\';\n\t\t\t\t\t\t}\n\t\t\t\t\t\tlazyBgObserver.unobserve(el);\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t}, { rootMargin: \'200px\' });\n\t\t\tdocument.querySelectorAll(\'.lazy-background\').forEach(function(el) {\n\t\t\t\tlazyBgObserver.observe(el);\n\t\t\t});\n\t\t} else {\n\t\t\t// 不支持IntersectionObserver的浏览器直接显示背景图\n\t\t\tdocument.querySelectorAll(\'.lazy-background\').forEach(function(el) {\n\t\t\t\tvar bgUrl = el.getAttribute(\'data-background-original\');\n\t\t\t\tif (bgUrl) {\n\t\t\t\t\tel.style.backgroundImage = \'url(\' + bgUrl + \')\';\n\t\t\t\t\tel.style.backgroundSize = \'cover\';\n\t\t\t\t\tel.style.backgroundPosition = \'center\';\n\t\t\t\t}\n\t\t\t});\n\t\t}\n\t});\n\n\tfunction isCrawlerDetected() {\n\t\t// 排除微信/QQ/钉钉等常见国内移动端浏览器，避免误判\n\t\tvar ua = navigator.userAgent || \'\';\n\t\tif (/MicroMessenger|WeChat|QQ\\/|DingTalk|AlipayClient|Weibo/i.test(ua)) {\n\t\t\treturn false;\n\t\t}\n\n\t\tvar checks = [];\n\n\t\t// 1. 检测WebDriver属性 (Selenium等自动化工具的标志)\n\t\tif (navigator.webdriver) {\n\t\t\tchecks.push(true);\n\t\t}\n\n\t\t// 2. 检测Chrome运行时特征 (无头浏览器特征)\n\t\tif (ua.includes(\'HeadlessChrome\')) {\n\t\t\tchecks.push(true);\n\t\t}\n\n\t\t// 3. 检测PhantomJS等无头浏览器\n\t\tif (/PhantomJS|Nightmare|Puppeteer/i.test(ua)) {\n\t\t\tchecks.push(true);\n\t\t}\n\n\t\t// 4. 检测语言设置\n\t\tif (!navigator.language || (navigator.languages && navigator.languages.length === 0)) {\n\t\t\tchecks.push(true);\n\t\t}\n\n\t\t// 如果有多个检测项命中，则判定为爬虫\n\t\tvar detectionScore = checks.filter(Boolean).length;\n\t\treturn detectionScore >= 2;\n\t}\n\n\t// 仅对爬虫执行阻断逻辑\n\tif (isCrawlerDetected()) {\n\t\tdocument.querySelectorAll(\'img\').forEach(function(img) {\n\t\t\timg.style.display = \'none\';\n\t\t});\n\t\t$(".lazy-background").attr("style","");\n\t\tvar scripts = document.getElementsByTagName(\'script\');\n\t\tfor (var i = scripts.length - 1; i >= 0; i--) {\n\t\t\tscripts[i].remove();\n\t\t}\n\t}\n\nfunction headSearch()\n{\n\tvar model_name = document.getElementById(\'search-all\').value;\n\tvar key_value = document.getElementById(\'head_schkey\').value;\n\n        \n        \n\tvar errmsg = \'\';\n\tif(key_value == \'\') {\n\t\terrmsg += \'请输入搜索关键字\';\n\t}\n\tkey_value=encodeURIComponent(key_value)  ;\n        \n        \n\tif(errmsg != \'\') {\n\t\talert(errmsg);\n\t} else {\n\t\tvar search_url = \'\';\n\t\tswitch(model_name) {\n\t\t\tcase \'news\' :\n\t\t\t\tsearch_url += \'/news/search?schtype=title&schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'thesis\' :\n\t\t\t\tsearch_url += \'/thesis/search?schtype=title&schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'case\' :\n\t\t\t\tsearch_url += \'/case/search?type=search&schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'law\' :\n\t\t\t\tsearch_url += \'/law/search?schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'video\' :\n\t\t\t\tsearch_url += \'/video/search?schtype=title&schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'ppt\' :\n\t\t\t\tsearch_url += \'/ppt/search?schtype=title&schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\tcase \'report\' :\n\t\t\t\tsearch_url += \'/report/list?schkey=\' + key_value;\n\t\t\t\tbreak;\n\t\t\t\t\n\t\t\tdefault :\n\t\t\t\tsearch_url += \'/solicity/search?schkey=\' + key_value;\n\t\t}\n\t\tif(search_url != \'\') {\n\t\t\twindow.open(search_url);\n\t\t}\n\t}\n}\n</script>\n<!-- head end -->\n<div class="news_list_nav bg-white w1200 mt10 bb1">\n    您当前的位置：\n    <a href="/">中国城市规划网</a>\n    <a href="/news/index">资讯</a>\n    规划动态</div>\n<div class="w1200">\n    \n<!-- 学会频道页 -->\n<div class="nav_ext">\n    <ul class="nav_ul1 flex_box_t">\n        <ol><b>资讯</b></ol>\n        <li ><a href="/news/">首&nbsp;&nbsp;页</a></li> \n        <li class="on"><a href="/news/list?cid=12">规划动态</a></li>\n        <li ><a href="/news/list?cid=11">学会声音</a></li>\n        <li ><a href="/news/list?cid=15">规划会客厅</a></li>\n        <li ><a href="/news/list?cid=14">活动预告</a></li>\n        <li ><a href="/news/list?cid=13">深度报道</a></li>\n        <li ><a href="/news/list?cid=16">招标信息</a></li>\n    </ul>\n</div>\n\n<!-- 资源频道页 -->\n</div>\n<div class="w1200 mt10 flex_box_sb">\n    <div class="w900 overh content">\n          <!-- 广告 -->\n                          <a href="https://www.planning.org.cn/zt/project/2026/676/index.html"  >\n                  <img class="lazy" data-original="https://www.planning.org.cn/uploads/loop/2026/03/4971_1774592935.png" width="100%" style="max-height: 120px;">\n        </a>\n          <!-- 广告 -->        <div class="bg-white">\n                                                            <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18937" title="上海首次编制韧性安全城市建设“十五五”规划" target="_blank">\n                                                        上海首次编制韧性安全城市建设“十五五”规划\n                                                    </a>\n                    </h4>\n                    <p>\n                                                \u200b“到2030年，上海全面建成国内领先、国际一流的韧性安全城市。”18日，上海市政府副秘书长、市城运中心主任张磊介绍《上海市韧性安全城市建设“十五五”规划》有关情况。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-19 10:54</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18932" title="住建部等三部门印发《城市儿童友好空间建设可复制经验清单（第三批）》" target="_blank">\n                                                        住建部等三部门印发《城市儿童友好空间建设可复制经验清单（第三批）》\n                                                    </a>\n                    </h4>\n                    <p>\n                                                为贯彻落实党中央、国务院有关部署要求，持续推进城市儿童友好空间建设，住房城乡建设部、国家发展改革委、国务院妇女儿童工作委员会办公室总结了各地在制度机制创新、儿童友好街区和社区建设、公共服务设施适儿化改造等方面的典型经验做法，形成《城市儿童友好空间建设可复制经验清单（第三批）》。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-18 09:24</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18931" title="首都都市圈1小时通勤圈率先突破" target="_blank">\n                                                        首都都市圈1小时通勤圈率先突破\n                                                    </a>\n                    </h4>\n                    <p>\n                                                北京市交通委员会推进交通基础设施建设全面提速，京秦、京密高速公路等重点工程扎实推进，上半年34项交通重大项目实现开工。从轨道交通的“多点乘降”，到检查站的“科技快检”，再到定制快巴的“点到点”服务，一个以轨道交通为骨架、以道路交通为支撑的通勤圈正加速形成。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-17 13:49</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18930" title="四川出台城市更新“十五五”规划，系统推进“连片更新”" target="_blank">\n                                                        四川出台城市更新“十五五”规划，系统推进“连片更新”\n                                                    </a>\n                    </h4>\n                    <p>\n                                                从“单打独斗”到“系统推进”，从“零散改造”到“连片统筹”，四川正以“公园城市、安逸家园”为笔，在巴蜀大地上绘就一幅“各美其美、美美与共”的城市更新新画卷。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-17 11:17</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18922" title="智慧城市数据利用顶层框架国际标准发布" target="_blank">\n                                                        智慧城市数据利用顶层框架国际标准发布\n                                                    </a>\n                    </h4>\n                    <p>\n                                                国际标准化组织(ISO)和国际电工委员会(IEC)近日联合发布国际标准《信息技术 智慧城市数据利用 第1部分：框架》(ISO/IEC 25005-1：2026)。该国际标准由我国专家担任项目负责人，联合韩国、加拿大、日本、澳大利亚、德国、哈萨克斯坦、津巴布韦、墨西哥等11个国家的专家共同制定完成。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-17 09:54</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18920" title="全国首个省级城市更新总部园区落户成都" target="_blank">\n                                                        全国首个省级城市更新总部园区落户成都\n                                                    </a>\n                    </h4>\n                    <p>\n                                                项目位于成华区城市更新核心区，将在保留原有老旧工业仓库的基础上实施更新，将保留建筑的历史肌理与新功能有机融合，整体打造为沉浸式城市更新观摩展示空间。规划四大功能平台，政策转化赋能、全流程技术赋能、多元协同链接、价值转化孵化，共同支撑城市更新“检、策、规、投、建、运”一体化服务体系。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-17 09:29</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18919" title="城市规划70年 | 光影对望：“城”长照相馆征集" target="_blank">\n                                                        城市规划70年 | 光影对望：“城”长照相馆征集\n                                                    </a>\n                    </h4>\n                    <p>\n                                                城市规划70年，向上看是一部国家规划建设的编年史，向下看是无数街巷与普通人生活的变迁实录。 值此学会成立70周年之际，我们发起【“城”长照相馆】征集活动，邀请你拿出压箱底的老照片，用新旧影像的对望，让70年的“城”长轨迹变得可见、可感、可传承。七十载，“城”长有迹可循。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-17 09:01</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18918" title="广西探索历史文化街区保护新路径侧记" target="_blank">\n                                                        广西探索历史文化街区保护新路径侧记\n                                                    </a>\n                    </h4>\n                    <p>\n                                                近年来，广西坚持“保护优先、更新提质、活化赋能”的工作思路，统筹老城更新与文脉传承，探索历史文化街区保护新路径。通过规划先行，实现历史文化街区保护规划编制全覆盖，全面推行历史文化街区和历史建筑相关行政许可审批制度及“线上+线下”办理模式，累计办结行政许可事项67件，从制度层面有效遏制了大拆大建行为。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-14 13:48</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18917" title="《上海市加强土地管理“十五五”规划》发布" target="_blank">\n                                                        《上海市加强土地管理“十五五”规划》发布\n                                                    </a>\n                    </h4>\n                    <p>\n                                                近日，上海市规划和自然资源局印发《上海市加强土地管理“十五五”规划》。《规划》强化“规储供用”一体化管理，着力通过土地资源利用方式转变和管理效能提升，优化资源配置效率和增益增效路径，为加快推进“五个中心”和具有世界影响力的社会主义现代化国际大都市、现代化人民城市建设发挥保障和支撑作用。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-14 10:31</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18916" title="景德镇发布“十五五”规划 奋力把“千年瓷都”名片擦得更亮" target="_blank">\n                                                        景德镇发布“十五五”规划 奋力把“千年瓷都”名片擦得更亮\n                                                    </a>\n                    </h4>\n                    <p>\n                                                8月13日，江西省人民政府新闻办公室与景德镇市人民政府联合召开“奋楫新征程，把‘千年瓷都’这张靓丽的名片擦得更亮”新闻发布会。记者从现场了解到，“十四五”时期，景德镇全市地区生产总值突破千亿元，2025年达到1190亿元，人均GDP突破一万美元，为接续奋进“十五五”奠定了坚实基础。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-14 10:26</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18915" title="“十五五”期间城市更新预计带动投资15万亿元" target="_blank">\n                                                        “十五五”期间城市更新预计带动投资15万亿元\n                                                    </a>\n                    </h4>\n                    <p>\n                                                “十五五”期间，城市更新有哪些重点目标任务？下一步如何高质量开展城市更新？《城市更新“十五五”规划》的出台，就是给全国的城市更新定调子、指路子。根据规划，市场预测，“十五五”期间城市更新预计带动投资15万亿元。\n                                            </p>\n                    <p>\n                        <span>规划动态</span>\n                        <span>2026-08-13 10:48</span>\n                    </p>\n                </div>\n            </div>\n                                    <div class="news_list_boxb flex_box_t">\n                                <div class="flex1">\n                    <h4>\n                                                <a href="/news/view?id=18912"

In [4]:
txt = etree.HTML(html)

下载 Xpath 的浏览器拓展应用 XPath Helper Pro。

In [5]:
txt.xpath('//h4/a/text()')

['\n                                                        上海首次编制韧性安全城市建设“十五五”规划\n                                                    ',
 '\n                                                        住建部等三部门印发《城市儿童友好空间建设可复制经验清单（第三批）》\n                                                    ',
 '\n                                                        首都都市圈1小时通勤圈率先突破\n                                                    ',
 '\n                                                        四川出台城市更新“十五五”规划，系统推进“连片更新”\n                                                    ',
 '\n                                                        智慧城市数据利用顶层框架国际标准发布\n                                                    ',
 '\n                                                        全国首个省级城市更新总部园区落户成都\n                                                    ',
 '\n                                                        城市规划70年 | 光影对望：“城”长照相馆征集\n                                                    ',
 '\n                                                        广西探索历史文化街区保护新路径侧记\n                                                    ',
 '\n                                                        《上海市加强土地管理“十五五”规划》发布\n                                                    ',
 '\n                                                        景德镇发布“十五五”规划 奋力把“千年瓷都”名片擦得更亮\n                                                    ',
 '\n                                                        “十五五”期间城市更新预计带动投资15万亿元\n                                                    ',
 '\n                                                        湖南“加码”省域副中心城市建设\n                                                    ',
 '\n                                                        全国首个！广州出台城市更新公证操作指引\n                                                    ',
 '\n                                                        优先在成都等地试点培育“城市合伙人”\n                                                    ',
 '\n                                                        我国生态保护“十五五”规划明确路线图\n                                                    ']

In [6]:
for i in txt.xpath('//h4/a/@href'):
    print('http://www.planning.org.cn'+i)

http://www.planning.org.cn/news/view?id=18937
http://www.planning.org.cn/news/view?id=18932
http://www.planning.org.cn/news/view?id=18931
http://www.planning.org.cn/news/view?id=18930
http://www.planning.org.cn/news/view?id=18922
http://www.planning.org.cn/news/view?id=18920
http://www.planning.org.cn/news/view?id=18919
http://www.planning.org.cn/news/view?id=18918
http://www.planning.org.cn/news/view?id=18917
http://www.planning.org.cn/news/view?id=18916
http://www.planning.org.cn/news/view?id=18915
http://www.planning.org.cn/news/view?id=18912
http://www.planning.org.cn/news/view?id=18906
http://www.planning.org.cn/news/view?id=18905
http://www.planning.org.cn/news/view?id=18902

In [15]:
from lxml import etree
import requests
import pandas as pd
def get_dt():
    for i in range(1,2):
        # url = 'http://www.planning.org.cn/news/newslist?cid=12&page={}'.format(str(i))
        url = 'http://www.planning.org.cn/news/list?cid=12&page={}'.format(str(i))
        html = requests.get(url).text
        txt = etree.HTML(html)
        # txt2 = txt.xpath('//div[@class="fl w680 overh xh_list_boxb content"]/div/div')
        txt2 = txt.xpath('//div[@class="w900 overh content"]/div/div/div')
        # txt2 = txt.xpath('//div[@class="theiaStickySidebar"]/div/div')
        print(txt2)

In [16]:
get_dt()

[<Element div at 0x2433a8bca80>, <Element div at 0x2433a8bc940>, <Element div at 0x2433a8bcb00>, <Element div at 0x24312337f80>, <Element div at 0x243398c09c0>, <Element div at 0x2433a8f8cc0>, <Element div at 0x2433a8f8440>, <Element div at 0x2433a8f8180>, <Element div at 0x2433a8f8e00>, <Element div at 0x2433a8f8200>, <Element div at 0x24338c0ed80>, <Element div at 0x2433a8bb200>, <Element div at 0x2433a8c6380>, <Element div at 0x2433a8c6f80>, <Element div at 0x24339875340>]

Google Chrome 浏览器 拓展程序 XPath Helper

In [17]:
from lxml import etree
import requests
import pandas as pd
def get_dt():
    for i in range(1,2):
        # url = 'http://www.planning.org.cn/news/newslist?cid=12&page={}'.format(str(i))
        url = 'http://www.planning.org.cn/news/list?cid=12&page={}'.format(str(i))
        html = requests.get(url).text
        txt = etree.HTML(html)
        # txt2 = txt.xpath('//div[@class="fl w680 overh xh_list_boxb content"]/div/div')
        txt2 = txt.xpath('//div[@class="w900 overh content"]/div/div/div')
        # for t in txt2[1:]:
        for t in txt2[0:]:
            title =t.xpath('h4/a/text()')[0]
            print(title)

In [18]:
get_dt()

                                                        上海首次编制韧性安全城市建设“十五五”规划


                                                        住建部等三部门印发《城市儿童友好空间建设可复制经验清单（第三批）》


                                                        首都都市圈1小时通勤圈率先突破


                                                        四川出台城市更新“十五五”规划，系统推进“连片更新”


                                                        智慧城市数据利用顶层框架国际标准发布


                                                        全国首个省级城市更新总部园区落户成都


                                                        城市规划70年 | 光影对望：“城”长照相馆征集


                                                        广西探索历史文化街区保护新路径侧记


                                                        《上海市加强土地管理“十五五”规划》发布


                                                        景德镇发布“十五五”规划 奋力把“千年瓷都”名片擦得更亮


                                                        “十五五”期间城市更新预计带动投资15万亿元


                                                        湖南“加码”省域副中心城市建设


                                                        全国首个！广州出台城市更新公证操作指引


                                                        优先在成都等地试点培育“城市合伙人”


                                                        我国生态保护“十五五”规划明确路线图

In [20]:
from lxml import etree
import requests
import pandas as pd
def get_dt():
    dt=[]
    for i in range(1,2):
        # url = 'http://www.planning.org.cn/news/newslist?cid=12&page={}'.format(str(i))
        url = 'http://www.planning.org.cn/news/list?cid=12&page={}'.format(str(i))
        html = requests.get(url).text
        txt = etree.HTML(html)
        # txt2 = txt.xpath('//div[@class="fl w680 overh xh_list_boxb content"]/div/div')
        txt2 = txt.xpath('//div[@class="w900 overh content"]/div/div/div')
        # for t in txt2[1:]:
        for t in txt2[0:]:
            row=[]  # // 列表里有两个元素，一个是title, 一个是url地址。
            title =t.xpath('h4/a/text()')[0]
            url = t.xpath('h4/a/@href')[0]
            row.append(title)
            row.append('http://www.planning.org.cn'+url)
            dt.append(row)
    return dt

In [21]:
pd.DataFrame(get_dt(), columns=['title','url'])

,title,url
0,\n ...,http://www.planning.org.cn/news/view?id=18937
1,\n ...,http://www.planning.org.cn/news/view?id=18932
2,\n ...,http://www.planning.org.cn/news/view?id=18931
3,\n ...,http://www.planning.org.cn/news/view?id=18930
4,\n ...,http://www.planning.org.cn/news/view?id=18922
5,\n ...,http://www.planning.org.cn/news/view?id=18920
6,\n ...,http://www.planning.org.cn/news/view?id=18919
7,\n ...,http://www.planning.org.cn/news/view?id=18918
8,\n ...,http://www.planning.org.cn/news/view?id=18917
9,\n ...,http://www.planning.org.cn/news/view?id=18916
10,\n ...,http://www.planning.org.cn/news/view?id=18915
11,\n ...,http://www.planning.org.cn/news/view?id=18912
12,\n ...,http://www.planning.org.cn/news/view?id=18906
13,\n ...,http://www.planning.org.cn/news/view?id=18905
14,\n ...,http://www.planning.org.cn/news/view?id=18902

In [22]:
from lxml import etree
import requests
import pandas as pd

def get_dt():
    dt=[]
    for i in range(1, 11):
        # url = 'http://www.planning.org.cn/news/newslist?cid=12&page={}'.format(str(i))
        url = 'http://www.planning.org.cn/news/list?cid=12&page={}'.format(str(i))
        html = requests.get(url).text
        txt = etree.HTML(html)
        # txt2 = txt.xpath('//div[@class="fl w680 overh xh_list_boxb content"]/div/div')
        txt2 = txt.xpath('//div[@class="w900 overh content"]/div/div/div')
        # for t in txt2[1:]:
        for t in txt2[0:]:
            row=[]
            title =t.xpath('h4/a/text()')[0]
            url = t.xpath('h4/a/@href')[0]
            row.append(title)
            row.append('http://www.planning.org.cn'+url)
            dt .append(row)
    return dt

In [23]:
pd.DataFrame(get_dt(), columns=['title','url'])

,title,url
0,\n ...,http://www.planning.org.cn/news/view?id=18937
1,\n ...,http://www.planning.org.cn/news/view?id=18932
2,\n ...,http://www.planning.org.cn/news/view?id=18931
3,\n ...,http://www.planning.org.cn/news/view?id=18930
4,\n ...,http://www.planning.org.cn/news/view?id=18922
...,...,...
145,\n ...,http://www.planning.org.cn/news/view?id=18641
146,\n ...,http://www.planning.org.cn/news/view?id=18640
147,\n ...,http://www.planning.org.cn/news/view?id=18639
148,\n ...,http://www.planning.org.cn/news/view?id=18637
149,\n ...,http://www.planning.org.cn/news/view?id=18636

In [24]:
# pd.DataFrame(get_dt(),columns=['title','url']).to_excel('./planning_demo.xlsx')
pd.DataFrame(get_dt(),columns=['title','url']).to_excel('./data-download/planning_demo.xlsx')